x-node-image: &node_image node:24

x-node-common: &node_common
  user: node
  volumes:
    - ./:/project
  working_dir: /project

services:
  node: &node
    <<: *node_common
    image: *node_image

  storybook-react:
    <<: *node
    command: 'yarn storybook'
    working_dir: /project/m3-react
    environment:
      STORYBOOK_ALLOWED_HOSTS: '.modulify.test'
    labels:
      traefik.port: 6006
      traefik.enable: 'true'
      traefik.http.routers.m3-react-modulify.rule: 'HostRegexp(`m3-react.modulify.{[^.]+}`)'
      traefik.http.routers.m3-react-modulify.priority: 1
      traefik.http.routers.m3-react-modulify.service: m3-react-modulify
      traefik.http.services.m3-react-modulify.loadbalancer.server.port: '6006'

  storybook-vue:
    <<: *node
    command: 'yarn storybook'
    working_dir: /project/m3-vue
    environment:
      STORYBOOK_ALLOWED_HOSTS: '.modulify.test'
    labels:
      traefik.port: 6006
      traefik.enable: 'true'
      traefik.http.routers.m3-vue-modulify.rule: 'HostRegexp(`m3-vue.modulify.{[^.]+}`)'
      traefik.http.routers.m3-vue-modulify.priority: 1
      traefik.http.routers.m3-vue-modulify.service: m3-vue-modulify
      traefik.http.services.m3-vue-modulify.loadbalancer.server.port: '6006'

  playwright:
    <<: *node_common
    build:
      context: .
      dockerfile: docker/playwright/Dockerfile
      args:
        NODE_IMAGE: *node_image
    environment:
      PLAYWRIGHT_BROWSERS_PATH: '/ms-playwright'
      CI: 'true'
    shm_size: '1gb'
    ipc: host
    init: true
